In [4]:
#imprimindo partes do array

l = [20,30,10,40]
print(l[1:3])
print(l[::2]) #iterra de 2 em dois a partir do 0

[30, 10]
[20, 10]


In [6]:
import numpy as np

a = np.array(l)
a

array([20, 30, 10, 40])

In [8]:
# array do numpy suporta os mesmos operadores das listas

print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [9]:
l

[20, 30, 10, 40]

In [11]:
# copiando lista e não renomeando a referencia com outro 
# esse tipo de copia não funciona para array numpy

l2 = l[:]
l2

[20, 30, 10, 40]

In [15]:
l2[0] = 1000
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [16]:
a

array([20, 30, 10, 40])

In [18]:
# esse tipo de copia é apenas adicionar mais um label a mesma referencia de um mesmo objeto
b = a[:]
b

array([20, 30, 10, 40])

In [19]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [ ]:
# preenche todo o array com um so numero

b[:] = 42
a

In [20]:
# a forma correta de copiar um array numpy é:

c = a.copy()
print(c)
print(a)

[1000   30   10   40]
[1000   30   10   40]


In [21]:
c[0] = 1000000
print(c)
print(a)

[1000000      30      10      40]
[1000   30   10   40]
